pipeline {
    agent any
    stages {
        stage('Checkout') {
            steps {
                script {
                    git url: 'https://github.com/rohithraj25/Insurance-Management.git'
                    def microservices = [
                        'working/cms-claim-service'
                    ]
                    microservices.each { serviceDir ->
                        echo "Checked out ${serviceDir}"
                    }
                }
            }
        }

        stage('Build Maven Projects') {
            steps {
                script {
                    def mavenProjects = [
                        'cms-claim-service'
                    ]
                    mavenProjects.each { projectDir ->
                        dir(projectDir) {
                            echo "Building Maven project ${projectDir}"
                            sh 'mvn clean package'
                        }
                    }
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                script {
                    def dockerImageTag = "cms-claim-service:latest"
                    dir('cms-claim-service') {
                        sh "docker build -t ${dockerImageTag} ."
                    }
                }
            }
        }

 stage('Clean Previous Container') {
            steps {
                script {
                    def containerName = "cms-claim-service-container"

                    // Stop and remove any existing container with the same name
                    sh """
                    if [ \$(docker ps -aq -f name=${containerName}) ]; then
                        docker stop ${containerName}
                        docker rm ${containerName}
                    fi
                    """
                }
            }
        }


        stage('Run Docker Container') {
            steps {
                script {
                    def dockerImageTag = "cms-claim-service:latest"
                    def containerName = "cms-claim-service-container"
                    sh "docker run -d --name ${containerName} -p 8083:8083 ${dockerImageTag}"
                }
            }
        }
    }
}

